import { Card } from "@/components/ui/card";
import { Link } from "wouter";
import { BookOpen, FileSearch, FolderOpen, Network, ShieldCheck, Stethoscope } from "lucide-react";

const navigation = [
  ["System Map", "/system-map"],
  ["Labs & Referrals", "/mandated-labs"],
  ["Source Vault", "/source-vault"],
  ["Merge Hub", "/merge-hub"],
  ["Care Coordination", "/coordination"],
  ["Risk Management", "/risk-management"],
];

export default function Home() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="bg-card border-b border-primary/40 py-2 px-4 text-center text-accent text-sm font-medium">EVIDENCE-LED DRAFT — Earlier acute/saline rescue content remains quarantined; clinical, legal, and eligibility decisions require qualified review.</div>
      <nav className="bg-card border-b border-border sticky top-0 z-50"><div className="container py-4 flex items-center justify-between gap-5"><Link href="/" className="text-xl font-bold text-accent shrink-0">Medical Advocacy Hub</Link><div className="flex gap-4 overflow-x-auto whitespace-nowrap text-sm">{navigation.map(([label, href]) => <Link key={href} href={href} className={label === "Merge Hub" ? "text-accent font-semibold hover:underline" : "text-foreground hover:text-accent transition"}>{label}</Link>)}</div></div></nav>

      <main>
        <section className="bg-gradient-to-b from-card to-background py-16 md:py-24"><div className="container max-w-6xl grid lg:grid-cols-[1.3fr_0.7fr] gap-8 items-start"><div className="space-y-7"><div className="flex items-center gap-3 text-accent"><FileSearch className="w-8 h-8" /><span className="uppercase tracking-[0.18em] text-xs font-semibold">Clinical coordination workspace</span></div><h1 className="text-5xl md:text-6xl font-bold text-accent leading-[1.04]">Evidence first. Whole-person review. Clear ownership.</h1><p className="text-xl text-muted-foreground max-w-3xl">A private working site for organizing records, requests, care domains, and follow-up decisions across immune/BMT, hematology, bone, vascular/heart, kidney, liver, lung, connective tissue, endocrine/mineral, metabolic, brain, GI, oncology, radiology, and eye care.</p><div className="flex flex-wrap gap-4"><Link href="/system-map" className="bg-accent text-accent-foreground font-bold px-6 py-3 hover:opacity-90 transition">Open system map</Link><Link href="/source-vault" className="border border-accent text-accent font-bold px-6 py-3 hover:bg-accent/10 transition">Open source vault</Link></div></div><aside className="bg-card border border-border p-6 space-y-5"><div className="flex gap-3"><ShieldCheck className="w-6 h-6 text-accent flex-shrink-0" /><div><h2 className="font-bold text-accent">How this site treats evidence</h2><p className="mt-2 text-sm text-muted-foreground">A chart excerpt remains an excerpt. A patient request remains a request. An educational screener remains non-diagnostic. Original reports and documented treating-team decisions are required before information becomes a confirmed clinical finding.</p></div></div><Link href="/merge-hub" className="inline-flex text-sm font-semibold text-accent hover:underline">Add an original source securely →</Link></aside></div></section>

        <section className="py-14"><div className="container max-w-6xl"><div className="flex items-end justify-between gap-6 flex-wrap"><div><p className="uppercase tracking-[0.16em] text-xs font-semibold text-accent">Start here</p><h2 className="mt-2 text-3xl font-bold text-accent">Four coordinated workstreams</h2></div><p className="max-w-xl text-sm text-muted-foreground">The site is structured so a provider, advocate, or patient can see what exists, what needs confirmation, who owns the next review, and where to find the source.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4 mt-8"><Card className="bg-card border-border p-6"><Network className="w-6 h-6 text-accent" /><h3 className="mt-4 font-bold text-accent">System map</h3><p className="mt-2 text-sm text-muted-foreground">All major clinical domains, source status, specialty ownership, and confirmation gaps.</p><Link href="/system-map" className="inline-block mt-4 text-sm font-semibold text-accent hover:underline">Review domains →</Link></Card><Card className="bg-card border-border p-6"><Stethoscope className="w-6 h-6 text-accent" /><h3 className="mt-4 font-bold text-accent">Labs & referrals</h3><p className="mt-2 text-sm text-muted-foreground">Source-led monitoring and referral requests, explicitly marked for clinician review.</p><Link href="/mandated-labs" className="inline-block mt-4 text-sm font-semibold text-accent hover:underline">Review requests →</Link></Card><Card className="bg-card border-border p-6"><FolderOpen className="w-6 h-6 text-accent" /><h3 className="mt-4 font-bold text-accent">Source vault</h3><p className="mt-2 text-sm text-muted-foreground">Catalog of available working sources, permissible use, and what still needs an original record.</p><Link href="/source-vault" className="inline-block mt-4 text-sm font-semibold text-accent hover:underline">Open catalog →</Link></Card><Card className="bg-card border-border p-6"><BookOpen className="w-6 h-6 text-accent" /><h3 className="mt-4 font-bold text-accent">Care resources</h3><p className="mt-2 text-sm text-muted-foreground">Coordination context, including PATH/CalAIM/ECM guidance and an intentionally unassigned SMF resource slot.</p><Link href="/source-vault" className="inline-block mt-4 text-sm font-semibold text-accent hover:underline">Review resources →</Link></Card></div></div></section>

        <section className="bg-card border-y border-border py-14"><div className="container max-w-6xl grid lg:grid-cols-[1fr_1fr] gap-8"><div><h2 className="text-3xl font-bold text-accent">Provider-ready review path</h2><p className="mt-4 text-muted-foreground">The site does not replace medical judgment. It gives each reviewing clinician a consistent path to an evidence-based decision.</p></div><ol className="grid sm:grid-cols-2 gap-5 text-sm text-muted-foreground"><li><strong className="block text-accent mb-2">1. Attach the original source</strong>Use signed reports, final imaging, lab values, pathology, and genetics records.</li><li><strong className="block text-accent mb-2">2. Assign the reviewing specialty</strong>Identify the clinician responsible for interpreting each issue.</li><li><strong className="block text-accent mb-2">3. Record the decision</strong>Document whether a request is accepted, modified, deferred, or declined and why.</li><li><strong className="block text-accent mb-2">4. Set a follow-up point</strong>Record the next test, symptom trigger, appointment, or coordination task.</li></ol></div></section>
      </main>

      <footer className="bg-background border-t border-border py-8"><div className="container max-w-6xl text-center text-muted-foreground text-sm"><p>Working clinical-review and advocacy archive. The site organizes sources and questions; it does not independently diagnose, prescribe, grant eligibility, or make legal findings.</p><p className="mt-3">Current revision: evidence-led source control and multi-system coordination.</p></div></footer>
    </div>
  );
}
